services:
  postgres:
    image: 'postgres:latest'
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '${DB_PORT}:${DB_PORT}'

  springboot:
    build: .
    depends_on:
      - postgres
    environment:
        URL: postgres
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
        GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
        JWT_SECRET: ${JWT_SECRET}
        JWT_EXPIRY_MS: ${JWT_EXPIRY_MS}
    ports:
      - "8080:8080"

volumes:
  pgdata: